[package]
name = "boms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanorand = { version = "0.6.1", features = ["wyrand"] }
arrayvec = "0.7.2"