[package]
name = "boms"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "bench"
harness = false

[profile.release]
lto = "thin"

[dev-dependencies]
criterion = "0.3.5"

[dependencies]
nanorand = { version = "0.6.1", features = ["wyrand"] }
arrayvec = "0.7.2"
